//Auth

export const LOGIN = 'LOGIN'
export const REQUEST_PASSWORD_RESET = 'REQUEST_PASSWORD_RESET'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const LOGIN_STATUS = 'LOGIN_STATUS'