export const addShipmentFields = [
    { name: 'shipmentRefNo', label: 'Reference number', type: 'text', disabled: true },
    { name: 'shipperName', label: 'Shipper name', type: 'text' },
    { name: 'shipperEmail', label: 'Shipper email', type: 'email' },
    { name: 'shipperPhone', label: 'Shipper Phone', type: 'text' },
    { name: 'shipperCountry', label: 'Shipper country', type: 'text' },
    { name: 'shipperState', label: 'Shipper state', type: 'text' },
    { name: 'shipperLocation', label: 'Shipper location', type: 'text' },
    { name: 'consigneeName', label: 'Consignee name', type: 'text' },
    { name: 'consigneeEmail', label: 'Consignee email', type: 'email' },
    { name: 'consigneePhone', label: 'Consignee phone', type: 'text' },
    { name: 'delliverLocation', label: 'Delliver location', type: 'text' },
    { name: 'deliveryCity', label: 'Delivery city', type: 'text' },
    { name: 'deliveryCountry', label: 'Delivery country', type: 'text' },
    { name: 'commodity', label: 'Commodity', type: 'text' },
    { name: 'numberOfPackages', label: 'Number of packages', type: 'number' },
    { name: 'pickupDate', label: 'Pickup date', type: 'date' },
    { name: 'deliveryDate', label: 'Delivery date', type: 'date' },
    { name: 'shipmentDate', label: 'Shipment date', type: 'date' },
    { name: 'sStatus', label: 'Status', type: 'text', select: true },
]